version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foodplan.rule=Host(`foodplan.yourdomain.com`)"
      - "traefik.http.routers.foodplan.entrypoints=websecure"
      - "traefik.http.routers.foodplan.tls=true"
      - "traefik.http.services.foodplan.loadbalancer.server.port=8000"
    networks:
      - traefik-public
      - foodplan-network
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=foodplan
      - POSTGRES_USER=foodplan
      - POSTGRES_PASSWORD=foodplan
    networks:
      - foodplan-network

  redis:
    image: redis:7-alpine
    networks:
      - foodplan-network

networks:
  traefik-public:
    external: true
  foodplan-network:
    internal: true

volumes:
  postgres_data: 